const TOKEN_TYPE = {
  ACCESS_TOKEN: "ACCESS",
  REFRESH_TOKEN: "REFRESH",
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_EMAIL: "VERIFY_EMAIL",
};

const PRODUCT_STATUS = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

module.exports = {
  TOKEN_TYPE,
  PRODUCT_STATUS,
};
